name: Upload Release Asset
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  linux:
    name: Upload Linux files
    runs-on: ubuntu-18.04
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.0.2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Checkout
        run: git clone git@github.com:microshine/ejbca-client.git --depth 1
      - name: Upload files to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: installers
          path: ejbca-client/LICENSE
  macos:
    name: Upload MAC files
    runs-on: macos-10.15
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.0.2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Checkout
        run: git clone git@github.com:microshine/ejbca-client.git --depth 1
      - name: Upload files to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: installers
          path: ejbca-client/README.md
  create_release:
    name: Create Release
    runs-on: ubuntu-18.04
    needs: [macos, linux]
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v1
        with:
          name: installers
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
      - name: Upload README.md
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: installers/README.md
          asset_name: README.md
          asset_content_type: text/plain
      - name: Upload LICENSE
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: installers/LICENSE
          asset_name: LICENSE
          asset_content_type: text/plain